[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
crossterm = "0.29.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
rustyline = "15.0.0"
