[package]
name = "todo_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
crossterm = "0.29.0"
rustyline = "15.0.0"
todo_core = { path = "../core" }
snafu = { workspace = true }
